version: "3.3"
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        restart: always
        volumes:
            - /opt/container-data/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    redisbrow:
        image: marian/rebrow
        container_name: redisbrow
        restart: always
        ports:
            - "8082:5001"
        links:
            - redis

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - /opt/container-data/mongo/data/:/data/db/

    mongoexpress:
        image: mongo-express
        container_name: mongoexpress
        restart: always
        ports:
            - "8081:8081"
        links:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
